import type { KnownModelMeta } from "../build-record";

export const COHERE_KNOWN_MODELS: Record<string, KnownModelMeta> = {
  "cohere-transcribe-arabic-07-2026": {
    name: "Cohere Transcribe Arabic",
    description:
      "Cohere's open-weight 2B speech-to-text model optimized for Arabic dialects and English spoken with an Arabic accent.",
    category: "speech_audio",
    parameter_count: 2_000_000_000,
    release_date: "2026-07-07",
    architecture: "Conformer encoder-decoder",
    status: "active",
    modalities: ["audio", "text"],
    capabilities: {
      transcription: true,
      streaming: true,
    },
    is_api_available: true,
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
    website_url:
      "https://docs.cohere.com/changelog/transcribe-arabic",
  },
  "north-mini-code-1-0": {
    name: "North Mini Code",
    description:
      "Cohere's open-weight 30B total and 3B active mixture-of-experts model for agentic software engineering, terminal agents, and local coding workflows.",
    category: "code",
    context_window: 262144,
    parameter_count: 30_000_000_000,
    release_date: "2026-06-09",
    architecture: "Sparse mixture-of-experts transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      tool_use: true,
      streaming: true,
    },
    is_api_available: true,
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
    website_url:
      "https://docs.cohere.com/changelog/north-mini-code-1-0",
  },
  "command-a-plus-05-2026": {
    name: "Command A+",
    description:
      "Cohere's open-weight multimodal mixture-of-experts model for vision, reasoning, translation, and agentic tasks, with 218B total and 25B active parameters.",
    category: "multimodal",
    context_window: 128000,
    parameter_count: 218_000_000_000,
    release_date: "2026-05-20",
    architecture: "Sparse mixture-of-experts transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      vision: true,
      reasoning: true,
      tool_use: true,
      translation: true,
      streaming: true,
    },
    is_api_available: true,
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
    website_url: "https://docs.cohere.com/docs/command-a-plus",
  },
  "cohere-transcribe-03-2026": {
    name: "Cohere Transcribe",
    description:
      "Cohere's open-weight 2B multilingual automatic speech recognition model for high-accuracy audio transcription.",
    category: "speech_audio",
    parameter_count: 2_000_000_000,
    release_date: "2026-03-26",
    architecture: "Conformer encoder-decoder",
    status: "active",
    modalities: ["audio", "text"],
    capabilities: {
      transcription: true,
      streaming: true,
    },
    is_api_available: true,
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
    website_url:
      "https://docs.cohere.com/changelog/cohere-transcribe-03-2026",
  },
  "rerank-v4.0-pro": {
    name: "Rerank v4.0 Pro",
    description:
      "Cohere's highest-quality multilingual reranking model for text and semi-structured data.",
    category: "embeddings",
    context_window: 32768,
    release_date: "2025-12-11",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reranking: true,
    },
    is_api_available: true,
    is_open_weights: false,
    license: "commercial",
    license_name: null,
    website_url: "https://docs.cohere.com/changelog/rerank-v4.0",
  },
  "rerank-v4.0-fast": {
    name: "Rerank v4.0 Fast",
    description:
      "Cohere's low-latency, high-throughput multilingual reranking model for text and semi-structured data.",
    category: "embeddings",
    context_window: 32768,
    release_date: "2025-12-11",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reranking: true,
    },
    is_api_available: true,
    is_open_weights: false,
    license: "commercial",
    license_name: null,
    website_url: "https://docs.cohere.com/changelog/rerank-v4.0",
  },
  "embed-v4.0": {
    name: "Embed v4.0",
    description:
      "Cohere's multimodal embedding model for text, images, and mixed text-image documents with configurable embedding dimensions.",
    category: "embeddings",
    context_window: 131072,
    status: "active",
    modalities: ["text", "image", "file"],
    capabilities: {
      vision: true,
      embeddings: true,
    },
    is_api_available: true,
    is_open_weights: false,
    license: "commercial",
    license_name: null,
    website_url: "https://docs.cohere.com/docs/models",
  },
  "tiny-aya-global": {
    name: "tiny-aya-global",
    description:
      "CohereLabs' compact multilingual Aya model for global text generation and understanding, published on Hugging Face with an 8K context window.",
    category: "llm",
    context_window: 8192,
    parameter_count: 3_350_000_000,
    release_date: "2026-02-13",
    status: "active",
    modalities: ["text"],
    capabilities: {
      streaming: true,
    },
    is_api_available: true,
    is_open_weights: true,
    license: "research_only",
    license_name: "CC-BY-NC-4.0",
    hf_model_id: "CohereLabs/tiny-aya-global",
    website_url: "https://huggingface.co/CohereLabs/tiny-aya-global",
  },
  "tiny-aya-earth": {
    name: "Tiny Aya Earth",
    description:
      "CohereLabs' compact open-weight multilingual model specialized for West Asian and African languages.",
    category: "llm",
    context_window: 8192,
    parameter_count: 3_350_000_000,
    release_date: "2026-02-13",
    status: "active",
    modalities: ["text"],
    capabilities: {
      streaming: true,
    },
    is_api_available: true,
    is_open_weights: true,
    license: "research_only",
    license_name: "CC-BY-NC-4.0",
    hf_model_id: "CohereLabs/tiny-aya-earth",
    website_url: "https://huggingface.co/CohereLabs/tiny-aya-earth",
  },
  "tiny-aya-fire": {
    name: "Tiny Aya Fire",
    description:
      "CohereLabs' compact open-weight multilingual model specialized for South Asian languages.",
    category: "llm",
    context_window: 8192,
    parameter_count: 3_350_000_000,
    release_date: "2026-02-13",
    status: "active",
    modalities: ["text"],
    capabilities: {
      streaming: true,
    },
    is_api_available: true,
    is_open_weights: true,
    license: "research_only",
    license_name: "CC-BY-NC-4.0",
    hf_model_id: "CohereLabs/tiny-aya-fire",
    website_url: "https://huggingface.co/CohereLabs/tiny-aya-fire",
  },
  "tiny-aya-water": {
    name: "Tiny Aya Water",
    description:
      "CohereLabs' compact open-weight multilingual model specialized for European and Asia-Pacific languages.",
    category: "llm",
    context_window: 8192,
    parameter_count: 3_350_000_000,
    release_date: "2026-02-13",
    status: "active",
    modalities: ["text"],
    capabilities: {
      streaming: true,
    },
    is_api_available: true,
    is_open_weights: true,
    license: "research_only",
    license_name: "CC-BY-NC-4.0",
    hf_model_id: "CohereLabs/tiny-aya-water",
    website_url: "https://huggingface.co/CohereLabs/tiny-aya-water",
  },
};
