/**
 * Google AI static model data.
 * Extracted from src/lib/data-sources/adapters/google-models.ts KNOWN_MODELS.
 */

import type { KnownModelMeta } from "../build-record";

export const GOOGLE_KNOWN_MODELS: Record<string, KnownModelMeta> = {
  // ---- Gemini 3 series ----
  "gemini-3-pro": {
    name: "Gemini 3 Pro",
    description:
      "Google's third-generation flagship multimodal model with a 1 million token context window. Delivers state-of-the-art performance across reasoning, coding, and long-context understanding.",
    category: "multimodal",
    context_window: 1000000,
    release_date: "2025-11-18",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image", "audio", "video"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      grounding: true,
      code_execution: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-3-flash": {
    name: "Gemini 3 Flash",
    description:
      "Fast, cost-efficient third-generation Gemini model with a 1 million token context window. Optimised for high-throughput applications requiring real-time multimodal responses.",
    category: "multimodal",
    context_window: 1000000,
    release_date: "2025-11-18",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image", "audio", "video"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      grounding: true,
      code_execution: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-3": {
    name: "Gemini 3",
    description:
      "Google's general Gemini 3 family for multimodal reasoning, coding, and long-context assistant workloads.",
    category: "multimodal",
    context_window: 1000000,
    release_date: "2025-11-18",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image", "audio", "video"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      grounding: true,
      code_execution: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-3.1-pro": {
    name: "Gemini 3.1 Pro",
    description:
      "Updated Gemini 3.1 flagship model for complex reasoning, coding, and long-context multimodal work.",
    category: "multimodal",
    context_window: 1000000,
    release_date: "2026-03-24",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image", "audio", "video"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      grounding: true,
      code_execution: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-3.1-flash-live": {
    name: "Gemini 3.1 Flash Live",
    description:
      "Low-latency Gemini 3.1 live model for real-time multimodal conversations, streaming assistance, and interactive agent workflows.",
    category: "multimodal",
    context_window: 1000000,
    release_date: "2026-03-24",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image", "audio", "video"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      streaming: true,
      function_calling: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-3.1-flash-image": {
    name: "Gemini 3.1 Flash Image",
    description:
      "Gemini 3.1 image-focused model for prompt-following image generation and multimodal creative workflows.",
    category: "image_generation",
    context_window: 1000000,
    release_date: "2026-03-24",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      image_generation: true,
      image_editing: true,
      vision: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },

  // ---- Gemini 2.5 series ----
  "gemini-2.5-pro": {
    name: "Gemini 2.5 Pro",
    description:
      "Google's most capable Gemini 2.5 model with a 1 million token context window and deep thinking mode. Achieves top performance on coding, math, and science benchmarks.",
    category: "multimodal",
    context_window: 1000000,
    release_date: "2025-03-25",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image", "audio", "video"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      grounding: true,
      code_execution: true,
      function_calling: true,
      extended_thinking: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-2.5-flash": {
    name: "Gemini 2.5 Flash",
    description:
      "Efficient Gemini 2.5 model combining fast inference with a 1 million token context. Features thinking mode for improved accuracy on complex tasks at lower cost than Pro.",
    category: "multimodal",
    context_window: 1000000,
    release_date: "2025-05-20",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image", "audio", "video"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      grounding: true,
      code_execution: true,
      function_calling: true,
      extended_thinking: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-2.5-flash-lite": {
    name: "Gemini 2.5 Flash Lite",
    description:
      "Lower-cost Gemini 2.5 Flash variant for high-throughput production use with lighter reasoning and multimodal capability.",
    category: "multimodal",
    context_window: 1000000,
    release_date: "2025-05-20",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image", "audio", "video"],
    capabilities: {
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },

  // ---- Gemini 2.0 series ----
  "gemini-2.0-flash": {
    name: "Gemini 2.0 Flash",
    description:
      "Next-generation Flash model with native tool use, multimodal live API, and a 1 million token context. Delivers Gemini 1.5 Pro quality at Flash speed and cost.",
    category: "multimodal",
    context_window: 1048576,
    release_date: "2025-02-05",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image", "audio", "video"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      grounding: true,
      code_execution: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-2.0-flash-lite": {
    name: "Gemini 2.0 Flash Lite",
    description:
      "Ultra-lightweight variant of Gemini 2.0 Flash designed for cost-sensitive, high-volume workloads. Retains the 1 million token context window with minimal inference cost.",
    category: "multimodal",
    context_window: 1048576,
    release_date: "2025-02-05",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },

  // ---- Gemini 1.5 series ----
  "gemini-1.5-pro": {
    name: "Gemini 1.5 Pro",
    description:
      "Mid-size multimodal model with an industry-leading 2 million token context window using Mixture-of-Experts architecture. Excels at long-document analysis and complex reasoning.",
    category: "multimodal",
    context_window: 2097152,
    release_date: "2024-05-15",
    architecture: "Transformer (MoE)",
    status: "active",
    modalities: ["text", "image", "audio", "video"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      grounding: true,
      code_execution: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-1.5-flash": {
    name: "Gemini 1.5 Flash",
    description:
      "Fast, versatile model with a 1 million token context window. Designed for high-frequency tasks requiring broad multimodal capability at accessible cost.",
    category: "multimodal",
    context_window: 1048576,
    release_date: "2024-05-15",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image", "audio", "video"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      grounding: true,
      code_execution: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },

  // ---- Gemma open models ----
  "gemma-4": {
    name: "Gemma 4",
    description:
      "Google's fourth-generation open-weight multimodal model family, released under Apache 2.0 for private deployment on your own hardware, cloud GPUs, and edge devices.",
    category: "multimodal",
    context_window: 128000,
    release_date: "2026-04-02",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
  },
  "gemma-4-31b": {
    name: "Gemma 4 31B",
    description:
      "31B Gemma 4 open-weight multimodal model for private deployment, local development, and production serving on your own infrastructure.",
    category: "multimodal",
    context_window: 128000,
    release_date: "2026-04-02",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
  },
  "gemma-4-31b-it": {
    name: "Gemma 4 31B IT",
    description:
      "Instruction-tuned 31B Gemma 4 model with open weights and Apache 2.0 licensing for private deployment and local multimodal applications.",
    category: "multimodal",
    context_window: 128000,
    release_date: "2026-04-02",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
  },
  "gemma-4-26b-a4b-it": {
    name: "Gemma 4 26B A4B IT",
    description:
      "Instruction-tuned Gemma 4 26B A4B variant released as open weights under Apache 2.0 for private and edge deployment.",
    category: "multimodal",
    context_window: 128000,
    release_date: "2026-04-02",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
  },
  "gemma-4-e2b-it": {
    name: "Gemma 4 E2B IT",
    description:
      "Compact instruction-tuned Gemma 4 E2B variant designed for efficient private deployment on constrained hardware.",
    category: "multimodal",
    context_window: 128000,
    release_date: "2026-04-02",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
  },
  "gemma-4-e4b-it": {
    name: "Gemma 4 E4B IT",
    description:
      "Compact instruction-tuned Gemma 4 E4B variant for private multimodal deployment on local and edge hardware.",
    category: "multimodal",
    context_window: 128000,
    release_date: "2026-04-02",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
  },
  "gemma-3": {
    name: "Gemma 3",
    description:
      "Google's third-generation open-weights language model family. Available in multiple sizes, suitable for on-device inference, fine-tuning, and research.",
    category: "llm",
    context_window: 128000,
    release_date: "2025-03-12",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      coding: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
  },
  "gemma-3n": {
    name: "Gemma 3n",
    description:
      "Compact multimodal Gemma 3n family for efficient on-device or resource-constrained inference with support for text, image, and audio inputs.",
    category: "multimodal",
    context_window: 32000,
    release_date: "2025-05-20",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image", "audio"],
    capabilities: {
      coding: true,
      function_calling: true,
      streaming: true,
      vision: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
  },
  "gemma-2": {
    name: "Gemma 2",
    description:
      "Second-generation open-weights model from Google. Offers competitive performance in a compact form factor; available in 2B, 9B, and 27B parameter variants.",
    category: "llm",
    context_window: 8192,
    release_date: "2024-06-27",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      coding: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
  },

  // ---- Image generation ----
  "imagen-3": {
    name: "Imagen 3",
    description:
      "Google's highest-quality text-to-image model. Produces photorealistic images with exceptional detail, lighting accuracy, and minimal artifacts.",
    category: "image_generation",
    context_window: null,
    release_date: "2024-08-01",
    architecture: "Diffusion",
    status: "active",
    modalities: ["text", "image"],
    capabilities: { image_generation: true, image_editing: true },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "imagen-4": {
    name: "Imagen 4",
    description:
      "Google's latest text-to-image model with improved prompt fidelity, typography, and photorealistic detail for creative production.",
    category: "image_generation",
    context_window: null,
    release_date: "2025-05-20",
    architecture: "Diffusion",
    status: "active",
    modalities: ["text", "image"],
    capabilities: { image_generation: true, image_editing: true },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "imagen-4-fast": {
    name: "Imagen 4 Fast",
    description:
      "Faster Imagen 4 variant for rapid text-to-image iteration while retaining current-generation Google image quality.",
    category: "image_generation",
    context_window: null,
    release_date: "2025-05-20",
    architecture: "Diffusion",
    status: "active",
    modalities: ["text", "image"],
    capabilities: { image_generation: true, image_editing: true },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },

  // ---- Video generation ----
  "veo-2": {
    name: "Veo 2",
    description:
      "Google's advanced video generation model capable of producing high-definition video clips from text and image prompts with improved physics understanding and motion coherence.",
    category: "video",
    context_window: null,
    release_date: "2024-12-01",
    architecture: "Diffusion (Video)",
    status: "active",
    modalities: ["text", "image", "video"],
    capabilities: { video_generation: true },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "veo-3.1": {
    name: "Veo 3.1",
    description:
      "Google's latest flagship video-generation model with stronger controllability, cinematic output, and native audio generation.",
    category: "video",
    context_window: null,
    release_date: "2026-03-24",
    architecture: "Diffusion (Video)",
    status: "active",
    modalities: ["text", "image", "video", "audio"],
    capabilities: { video_generation: true, text_to_speech: true },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "veo-3.1-fast": {
    name: "Veo 3.1 Fast",
    description:
      "Faster Veo 3.1 variant for iterative video ideation and lower-latency creative workflows.",
    category: "video",
    context_window: null,
    release_date: "2026-03-24",
    architecture: "Diffusion (Video)",
    status: "active",
    modalities: ["text", "image", "video", "audio"],
    capabilities: { video_generation: true, text_to_speech: true },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "veo-3": {
    name: "Veo 3",
    description:
      "Google video-generation family for cinematic prompt-to-video workflows with improved motion, scene coherence, and native audio output.",
    category: "video",
    context_window: null,
    release_date: "2025-05-20",
    architecture: "Diffusion (Video)",
    status: "active",
    modalities: ["text", "image", "video", "audio"],
    capabilities: { video_generation: true, text_to_speech: true },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
};

const GOOGLE_KNOWN_MODEL_FAMILY_PREFIXES = [
  "gemma-3n-",
  "gemma-3-",
  "gemma-4-",
] as const;

export function resolveGoogleKnownModelMeta(modelId: string): KnownModelMeta | undefined {
  const exact = GOOGLE_KNOWN_MODELS[modelId];
  if (exact) return exact;

  for (const familyPrefix of GOOGLE_KNOWN_MODEL_FAMILY_PREFIXES) {
    if (modelId.startsWith(familyPrefix)) {
      return GOOGLE_KNOWN_MODELS[familyPrefix.slice(0, -1)];
    }
  }

  return undefined;
}
