/**
 * Google AI static model data.
 * Extracted from src/lib/data-sources/adapters/google-models.ts KNOWN_MODELS.
 */

import type { KnownModelMeta } from "../build-record";

export const GOOGLE_KNOWN_MODELS: Record<string, KnownModelMeta> = {
  // ---- Current stable Gemini models ----
  "gemini-3.6-flash": {
    name: "Gemini 3.6 Flash",
    description:
      "Google's latest stable Flash model, optimized for efficient agentic execution, code generation, spatial reasoning, and high-throughput multimodal work.",
    category: "multimodal",
    context_window: 1048576,
    release_date: "2026-07-21",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image", "audio", "video"],
    website_url:
      "https://ai.google.dev/gemini-api/docs/models/gemini-3.6-flash",
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      grounding: true,
      code_execution: true,
      computer_use: true,
      function_calling: true,
      streaming: true,
    },
    is_api_available: true,
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-3.5-flash": {
    name: "Gemini 3.5 Flash",
    description:
      "Google's stable high-intelligence Flash model for sustained agentic and coding tasks, subagent deployment, and long-horizon multimodal workflows.",
    category: "multimodal",
    context_window: 1048576,
    release_date: "2026-05-19",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image", "audio", "video"],
    website_url:
      "https://ai.google.dev/gemini-api/docs/models/gemini-3.5-flash",
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      grounding: true,
      code_execution: true,
      computer_use: true,
      function_calling: true,
      streaming: true,
    },
    is_api_available: true,
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-3.5-flash-lite": {
    name: "Gemini 3.5 Flash-Lite",
    description:
      "Google's stable low-latency and cost-efficient Gemini model for high-volume subagent tasks, document parsing, and lightweight multimodal automation.",
    category: "multimodal",
    context_window: 1048576,
    release_date: "2026-07-21",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image", "audio", "video"],
    website_url:
      "https://ai.google.dev/gemini-api/docs/models/gemini-3.5-flash-lite",
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      grounding: true,
      code_execution: true,
      computer_use: true,
      function_calling: true,
      streaming: true,
    },
    is_api_available: true,
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },

  // ---- Current specialist models ----
  "gemini-3.5-live-translate-preview": {
    name: "Gemini 3.5 Live Translate",
    description:
      "Google's low-latency audio-to-audio model for real-time translation of spoken conversations across more than 70 languages.",
    category: "speech_audio",
    context_window: 131072,
    release_date: "2026-06-09",
    architecture: "Transformer (live audio)",
    status: "preview",
    modalities: ["audio", "text"],
    website_url:
      "https://ai.google.dev/gemini-api/docs/models/gemini-3.5-live-translate-preview",
    capabilities: {
      translation: true,
      transcription: true,
      audio_generation: true,
      streaming: true,
    },
    is_api_available: true,
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-robotics-er-2-preview": {
    name: "Gemini Robotics ER 2",
    description:
      "Google's latest embodied-reasoning model for spatial reasoning, robot video understanding, multi-robot orchestration, and multi-step tool use.",
    category: "specialized",
    context_window: 131072,
    release_date: "2026-07-30",
    architecture: "Vision-language model",
    status: "preview",
    modalities: ["text", "image", "video", "audio"],
    website_url: "https://ai.google.dev/gemini-api/docs/robotics-overview",
    capabilities: {
      reasoning: true,
      vision: true,
      robotics: true,
      code_execution: true,
      computer_use: true,
      function_calling: true,
      structured_outputs: true,
    },
    is_api_available: true,
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-robotics-er-2-streaming-preview": {
    name: "Gemini Robotics ER 2 Streaming",
    description:
      "Low-latency streaming endpoint for Gemini Robotics ER 2, designed for real-time robot agents processing continuous audio and video.",
    category: "specialized",
    context_window: 131072,
    release_date: "2026-07-30",
    architecture: "Vision-language model (streaming)",
    status: "preview",
    modalities: ["text", "image", "video", "audio"],
    website_url: "https://ai.google.dev/gemini-api/docs/robotics-overview",
    capabilities: {
      reasoning: true,
      vision: true,
      robotics: true,
      function_calling: true,
      streaming: true,
    },
    is_api_available: true,
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-robotics-er-1.6-preview": {
    name: "Gemini Robotics ER 1.6",
    description:
      "Previous Google embodied-reasoning preview model, scheduled for shutdown on August 31, 2026 and superseded by Gemini Robotics ER 2.",
    category: "specialized",
    context_window: 131072,
    release_date: "2026-04-14",
    architecture: "Vision-language model",
    status: "deprecated",
    modalities: ["text", "image", "video", "audio"],
    website_url: "https://ai.google.dev/gemini-api/docs/robotics-overview",
    capabilities: {
      reasoning: true,
      vision: true,
      robotics: true,
      code_execution: true,
      computer_use: true,
      function_calling: true,
      structured_outputs: true,
    },
    is_api_available: true,
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-embedding-2": {
    name: "Gemini Embedding 2",
    description:
      "Google's stable multimodal embedding model for cross-modal search, retrieval, recommendations, and RAG over text, images, video, audio, and PDFs.",
    category: "embeddings",
    context_window: 8192,
    release_date: "2026-04-22",
    architecture: "Transformer (embedding)",
    status: "active",
    modalities: ["text", "image", "video", "audio"],
    website_url:
      "https://ai.google.dev/gemini-api/docs/models/gemini-embedding-2",
    capabilities: {
      embeddings: true,
    },
    is_api_available: true,
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-3.1-flash-lite-image": {
    name: "Gemini 3.1 Flash-Lite Image",
    description:
      "Nano Banana 2 Lite, Google's stable ultra-low-latency model for cost-efficient image generation and editing in high-volume interactive applications.",
    category: "image_generation",
    context_window: 65536,
    release_date: "2026-06-30",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    website_url:
      "https://ai.google.dev/gemini-api/docs/models/gemini-3.1-flash-lite-image",
    capabilities: {
      image_generation: true,
      image_editing: true,
      function_calling: true,
      vision: true,
    },
    is_api_available: true,
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-omni-flash-preview": {
    name: "Gemini Omni Flash",
    description:
      "Google's preview multimodal model for fast conversational video generation and editing from text, images, audio, and video.",
    category: "video",
    context_window: 1048576,
    release_date: "2026-06-30",
    architecture: "Native multimodal generation",
    status: "preview",
    modalities: ["text", "image", "audio", "video"],
    website_url: "https://ai.google.dev/gemini-api/docs/omni",
    capabilities: {
      video_generation: true,
      video_editing: true,
      audio_generation: true,
      vision: true,
    },
    is_api_available: true,
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },

  // ---- Gemini 3 series ----
  "gemini-3-pro-preview": {
    name: "Gemini 3 Pro Preview",
    description:
      "Former Gemini 3 Pro preview endpoint. Google shut it down on March 9, 2026 and replaced it with Gemini 3.1 Pro Preview.",
    category: "multimodal",
    context_window: 1000000,
    release_date: "2025-11-18",
    architecture: "Transformer",
    status: "archived",
    is_api_available: false,
    modalities: ["text", "image", "audio", "video"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      grounding: true,
      code_execution: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-3-flash-preview": {
    name: "Gemini 3 Flash Preview",
    description:
      "Fast, cost-efficient third-generation Gemini model with a 1 million token context window. Optimised for high-throughput applications requiring real-time multimodal responses.",
    category: "multimodal",
    context_window: 1000000,
    release_date: "2025-12-17",
    architecture: "Transformer",
    status: "preview",
    is_api_available: true,
    modalities: ["text", "image", "audio", "video"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      grounding: true,
      code_execution: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-3": {
    name: "Gemini 3",
    description:
      "Gemini 3 family index retained for historical catalog continuity. Use a concrete Gemini 3.x endpoint for API workloads.",
    category: "multimodal",
    context_window: 1000000,
    release_date: "2025-11-18",
    architecture: "Transformer",
    status: "archived",
    is_api_available: false,
    modalities: ["text", "image", "audio", "video"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      grounding: true,
      code_execution: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-3.1-pro-preview": {
    name: "Gemini 3.1 Pro Preview",
    description:
      "Updated Gemini 3.1 flagship model for complex reasoning, coding, and long-context multimodal work. Improves on Gemini 2.5 Pro with stronger state-of-the-art performance and broad availability across the Gemini API and Vertex AI.",
    category: "multimodal",
    context_window: 1048576,
    release_date: "2026-02-19",
    architecture: "Transformer",
    status: "preview",
    modalities: ["text", "image", "audio", "video"],
    website_url:
      "https://ai.google.dev/gemini-api/docs/models/gemini-3.1-pro-preview",
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      grounding: true,
      code_execution: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-3.1-flash-live-preview": {
    name: "Gemini 3.1 Flash Live Preview",
    description:
      "Low-latency Gemini 3.1 live model for real-time multimodal conversations, streaming assistance, and interactive agent workflows.",
    category: "speech_audio",
    context_window: 131072,
    release_date: "2026-03-11",
    architecture: "Transformer",
    status: "preview",
    modalities: ["text", "image", "audio", "video"],
    website_url:
      "https://ai.google.dev/gemini-api/docs/models/gemini-3.1-flash-live-preview",
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      streaming: true,
      function_calling: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-3.1-flash-image": {
    name: "Gemini 3.1 Flash Image",
    description:
      "Gemini 3.1 image-focused model for high-fidelity prompt-following image generation and faster advanced editing. Brings Nano Banana Pro-level quality and reasoning to the faster Flash tier.",
    category: "image_generation",
    context_window: 65536,
    release_date: "2026-05-28",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    website_url:
      "https://ai.google.dev/gemini-api/docs/models/gemini-3.1-flash-image",
    capabilities: {
      image_generation: true,
      image_editing: true,
      vision: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-3-pro-image": {
    name: "Gemini 3 Pro Image",
    description:
      "Google's stable professional image generation and editing model for high-fidelity visual creation, complex layouts, and precise text rendering.",
    category: "image_generation",
    context_window: 65536,
    release_date: "2026-05-28",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    website_url:
      "https://ai.google.dev/gemini-api/docs/models/gemini-3-pro-image",
    capabilities: {
      image_generation: true,
      image_editing: true,
      vision: true,
    },
    is_api_available: true,
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-3.1-flash-tts-preview": {
    name: "Gemini 3.1 Flash TTS Preview",
    description:
      "Google's Gemini 3.1 text-to-speech model for expressive, controllable speech generation with native multi-speaker dialogue, 70+ language support, and audio tags for delivery control.",
    category: "speech_audio",
    context_window: 8192,
    release_date: "2026-04-13",
    architecture: "Transformer",
    status: "preview",
    modalities: ["text", "audio"],
    website_url:
      "https://ai.google.dev/gemini-api/docs/models/gemini-3.1-flash-tts-preview",
    capabilities: {
      speech: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-3.1-flash-lite": {
    name: "Gemini 3.1 Flash Lite",
    description:
      "Lower-cost Gemini 3.1 Flash Lite model for high-throughput multimodal assistant workloads. Outperforms Gemini 2.5 Flash on high-volume workloads while delivering faster time-to-first-token and output speed.",
    category: "multimodal",
    context_window: 1048576,
    release_date: "2026-05-07",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image", "audio", "video"],
    capabilities: {
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
    website_url:
      "https://blog.google/innovation-and-ai/models-and-research/gemini-models/gemini-3-1-flash-lite/",
  },
  "lyria-3": {
    name: "Lyria 3",
    description:
      "Google DeepMind music generation model for creating 30-second tracks from text or images with lyrics, creative control, and rich arrangement.",
    category: "speech_audio",
    release_date: "2026-02-18",
    architecture: "Latent diffusion",
    status: "active",
    modalities: ["text", "image", "audio"],
    website_url: "https://deepmind.google/models/model-cards/lyria-3/",
    capabilities: {
      audio_generation: true,
      vision: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "lyria-3-pro-preview": {
    name: "Lyria 3 Pro Preview",
    description:
      "Google DeepMind's higher-end Lyria 3 music generation tier for richer prompt control, lyrics, and production-quality soundtrack creation.",
    category: "speech_audio",
    release_date: "2026-03-25",
    architecture: "Latent diffusion",
    status: "preview",
    modalities: ["text", "image", "audio"],
    website_url: "https://ai.google.dev/gemini-api/docs/music-generation",
    capabilities: {
      audio_generation: true,
      vision: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "lyria-3-clip-preview": {
    name: "Lyria 3 Clip Preview",
    description:
      "Google's Lyria 3 preview model for generating 30-second music clips, loops, and prompt experiments from text or image inputs.",
    category: "speech_audio",
    release_date: "2026-03-25",
    architecture: "Latent diffusion",
    status: "preview",
    modalities: ["text", "image", "audio"],
    website_url: "https://ai.google.dev/gemini-api/docs/music-generation",
    capabilities: {
      audio_generation: true,
      vision: true,
    },
    is_api_available: true,
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "nano-banana-2": {
    name: "Nano Banana 2",
    description:
      "Google's fast image generation and editing model with stronger instruction following, higher visual fidelity, and grounded multi-image workflows.",
    category: "image_generation",
    release_date: "2026-02-26",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    website_url: "https://blog.google/innovation-and-ai/technology/ai/nano-banana-2/",
    capabilities: {
      image_generation: true,
      image_editing: true,
      vision: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "nano-banana-pro": {
    name: "Nano Banana Pro",
    description:
      "Google DeepMind's Gemini 3 Pro Image model for studio-quality image generation and editing across Gemini, AI Studio, Vertex AI, and other Google products.",
    category: "image_generation",
    release_date: "2025-11-20",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    website_url: "https://blog.google/innovation-and-ai/products/nano-banana-pro/",
    capabilities: {
      image_generation: true,
      image_editing: true,
      vision: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  upscaler: {
    name: "Upscaler",
    description:
      "Google image upscaling model for 2x and 4x enhancement in the Gemini image stack and related Google creative surfaces.",
    category: "specialized",
    release_date: "2026-02-12",
    architecture: "Transformer",
    status: "active",
    modalities: ["image"],
    capabilities: {
      image_editing: true,
      vision: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },

  // ---- Gemini 2.5 series ----
  "gemini-2.5-pro": {
    name: "Gemini 2.5 Pro",
    description:
      "Google's most capable Gemini 2.5 model with a 1 million token context window and deep thinking mode. Google lists it on the Gemini API deprecations schedule with Gemini 3 Pro as the recommended replacement.",
    category: "multimodal",
    context_window: 1000000,
    release_date: "2025-03-25",
    architecture: "Transformer",
    status: "deprecated",
    modalities: ["text", "image", "audio", "video"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      grounding: true,
      code_execution: true,
      function_calling: true,
      extended_thinking: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-2.5-flash": {
    name: "Gemini 2.5 Flash",
    description:
      "Efficient Gemini 2.5 model combining fast inference with a 1 million token context. Google lists this stable Gemini 2.5 Flash model on the Gemini API deprecations schedule with shutdown no earlier than June 2026.",
    category: "multimodal",
    context_window: 1000000,
    release_date: "2025-05-20",
    architecture: "Transformer",
    status: "deprecated",
    modalities: ["text", "image", "audio", "video"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      grounding: true,
      code_execution: true,
      function_calling: true,
      extended_thinking: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-2.5-flash-lite": {
    name: "Gemini 2.5 Flash Lite",
    description:
      "Lower-cost Gemini 2.5 Flash variant for high-throughput production use with lighter reasoning and multimodal capability. Google lists it on the Gemini API deprecations schedule with shutdown no earlier than July 2026.",
    category: "multimodal",
    context_window: 1000000,
    release_date: "2025-05-20",
    architecture: "Transformer",
    status: "deprecated",
    modalities: ["text", "image", "audio", "video"],
    capabilities: {
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-2.5": {
    name: "Gemini 2.5",
    description:
      "Google's Gemini 2.5 family for long-context multimodal reasoning, coding, and assistant workloads. The stable Gemini 2.5 line is on Google's deprecations schedule and is being superseded by the Gemini 3 generation.",
    category: "multimodal",
    context_window: 1000000,
    release_date: "2025-03-25",
    architecture: "Transformer",
    status: "deprecated",
    modalities: ["text", "image", "audio", "video"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      grounding: true,
      code_execution: true,
      function_calling: true,
      extended_thinking: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-2.5-flash-native": {
    name: "Gemini 2.5 Flash Native Audio",
    description:
      "Gemini 2.5 Flash native-audio family for low-latency voice interactions, streaming conversations, and multimodal assistant experiences.",
    category: "multimodal",
    context_window: 131072,
    release_date: "2025-09-23",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "audio", "image", "video"],
    capabilities: {
      reasoning: true,
      vision: true,
      function_calling: true,
      streaming: true,
      text_to_speech: true,
      speech_to_text: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },

  // ---- Gemini 2.0 series ----
  "gemini-2.0-flash": {
    name: "Gemini 2.0 Flash",
    description:
      "Former Gemini 2.0 Flash endpoint. Google shut this model down on June 1, 2026 and recommends Gemini 3.6 Flash as its replacement.",
    category: "multimodal",
    context_window: 1048576,
    release_date: "2025-02-05",
    architecture: "Transformer",
    status: "archived",
    is_api_available: false,
    modalities: ["text", "image", "audio", "video"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      grounding: true,
      code_execution: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-2.0-flash-lite": {
    name: "Gemini 2.0 Flash Lite",
    description:
      "Former low-cost Gemini 2.0 Flash-Lite endpoint. Google shut this model down on June 1, 2026 and recommends Gemini 3.1 Flash-Lite as its replacement.",
    category: "multimodal",
    context_window: 1048576,
    release_date: "2025-02-05",
    architecture: "Transformer",
    status: "archived",
    is_api_available: false,
    modalities: ["text", "image"],
    capabilities: {
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-2": {
    name: "Gemini 2",
    description:
      "Historical Gemini 2 family retained for catalog continuity after its production Flash endpoints were shut down.",
    category: "multimodal",
    context_window: 1048576,
    release_date: "2025-02-05",
    architecture: "Transformer",
    status: "archived",
    is_api_available: false,
    modalities: ["text", "image", "audio", "video"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      grounding: true,
      code_execution: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },

  // ---- Gemini 1.5 series ----
  "gemini-1.5-pro": {
    name: "Gemini 1.5 Pro",
    description:
      "Historical long-context multimodal model. Google shut down the Gemini 1.5 Pro endpoint on September 29, 2025.",
    category: "multimodal",
    context_window: 2097152,
    release_date: "2024-05-15",
    architecture: "Transformer (MoE)",
    status: "archived",
    is_api_available: false,
    modalities: ["text", "image", "audio", "video"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      grounding: true,
      code_execution: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "gemini-1.5-flash": {
    name: "Gemini 1.5 Flash",
    description:
      "Historical high-throughput multimodal model. Google shut down the Gemini 1.5 Flash endpoint on September 29, 2025.",
    category: "multimodal",
    context_window: 1048576,
    release_date: "2024-05-15",
    architecture: "Transformer",
    status: "archived",
    is_api_available: false,
    modalities: ["text", "image", "audio", "video"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      grounding: true,
      code_execution: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },

  // ---- Gemma open models ----
  "gemma-4": {
    name: "Gemma 4",
    description:
      "Google's fourth-generation open-weight multimodal model family, released under Apache 2.0 for private deployment on your own hardware, cloud GPUs, and edge devices.",
    category: "multimodal",
    context_window: 128000,
    release_date: "2026-04-02",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
  },
  "gemma-4-31b": {
    name: "Gemma 4 31B",
    description:
      "31B Gemma 4 open-weight multimodal model for private deployment, local development, and production serving on your own infrastructure.",
    category: "multimodal",
    context_window: 128000,
    release_date: "2026-04-02",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
  },
  "gemma-4-31b-it": {
    name: "Gemma 4 31B IT",
    description:
      "Instruction-tuned 31B Gemma 4 model with open weights and Apache 2.0 licensing for private deployment and local multimodal applications.",
    category: "multimodal",
    context_window: 128000,
    release_date: "2026-04-02",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
  },
  "gemma-4-26b-a4b-it": {
    name: "Gemma 4 26B A4B IT",
    description:
      "Instruction-tuned Gemma 4 26B A4B variant released as open weights under Apache 2.0 for private and edge deployment.",
    category: "multimodal",
    context_window: 128000,
    release_date: "2026-04-02",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
  },
  "gemma-4-e2b-it": {
    name: "Gemma 4 E2B IT",
    description:
      "Compact instruction-tuned Gemma 4 E2B variant designed for efficient private deployment on constrained hardware.",
    category: "multimodal",
    context_window: 128000,
    release_date: "2026-04-02",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
  },
  "gemma-4-e4b-it": {
    name: "Gemma 4 E4B IT",
    description:
      "Compact instruction-tuned Gemma 4 E4B variant for private multimodal deployment on local and edge hardware.",
    category: "multimodal",
    context_window: 128000,
    release_date: "2026-04-02",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
  },
  "gemma-3": {
    name: "Gemma 3",
    description:
      "Google's third-generation open-weights language model family. Available in multiple sizes, suitable for on-device inference, fine-tuning, and research.",
    category: "llm",
    context_window: 128000,
    release_date: "2025-03-12",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      coding: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
  },
  "gemma-3n": {
    name: "Gemma 3n",
    description:
      "Compact multimodal Gemma 3n family for efficient on-device or resource-constrained inference with support for text, image, and audio inputs.",
    category: "multimodal",
    context_window: 32000,
    release_date: "2025-05-20",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image", "audio"],
    capabilities: {
      coding: true,
      function_calling: true,
      streaming: true,
      vision: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
  },
  "gemma-3n-e4b-it-litert-lm": {
    name: "gemma-3n-E4B-it-litert-lm",
    description:
      "Google Gemma 3n LiteRT open-weight text variant for efficient on-device inference with Gemma 3n-family capabilities and a 32K token context window.",
    category: "llm",
    context_window: 32000,
    release_date: "2025-06-06",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      coding: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
    hf_model_id: "google/gemma-3n-E4B-it-litert-lm",
    website_url: "https://huggingface.co/google/gemma-3n-E4B-it-litert-lm",
  },
  "gemma-2": {
    name: "Gemma 2",
    description:
      "Second-generation open-weights model from Google. Offers competitive performance in a compact form factor; available in 2B, 9B, and 27B parameter variants.",
    category: "llm",
    context_window: 8192,
    release_date: "2024-06-27",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      coding: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
  },
  "gemini-embedding-001": {
    name: "Gemini Embedding 001",
    description:
      "Google's stable Gemini embeddings model for semantic search, retrieval, clustering, and vector indexing workflows.",
    category: "embeddings",
    context_window: 2048,
    release_date: "2025-07-14",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      streaming: false,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  aqa: {
    name: "Attributed Question Answering (AQA)",
    description:
      "Google's grounded question-answering model for producing answers tied to supplied source passages, with answerability scoring in the response flow.",
    category: "specialized",
    context_window: 7168,
    release_date: "2023-12-13",
    architecture: "Grounded question answering",
    status: "active",
    modalities: ["text"],
    capabilities: {
      grounded_qa: true,
      retrieval_augmented_generation: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
    website_url: "https://ai.google.dev/gemini-api/docs/changelog",
  },
  "gemini-2.5-flash-image": {
    name: "Gemini 2.5 Flash Image",
    description:
      "Google's stable Gemini image-generation and image-editing model for high-volume visual creation with native multimodal understanding.",
    category: "multimodal",
    context_window: 65536,
    release_date: "2025-10-02",
    architecture: "Native multimodal generation",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      image_generation: true,
      vision: true,
      structured_outputs: true,
      streaming: false,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
    website_url: "https://ai.google.dev/gemini-api/docs/models/gemini-2.5-flash-image",
  },

  // ---- Image generation ----
  "imagen-3": {
    name: "Imagen 3",
    description:
      "Historical Google text-to-image model retained after its production endpoint was shut down.",
    category: "image_generation",
    context_window: null,
    release_date: "2024-08-01",
    architecture: "Diffusion",
    status: "archived",
    is_api_available: false,
    modalities: ["text", "image"],
    capabilities: { image_generation: true, image_editing: true },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "imagen-4": {
    name: "Imagen 4",
    description:
      "Google text-to-image model with improved prompt fidelity, typography, and photorealistic detail. It is deprecated in favor of Gemini 3.1 Flash Image.",
    category: "image_generation",
    context_window: null,
    release_date: "2025-06-24",
    architecture: "Diffusion",
    status: "deprecated",
    is_api_available: true,
    modalities: ["text", "image"],
    capabilities: { image_generation: true, image_editing: true },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "imagen-4-fast": {
    name: "Imagen 4 Fast",
    description:
      "Faster Imagen 4 variant for rapid text-to-image iteration. It is deprecated in favor of Gemini 3.1 Flash Image.",
    category: "image_generation",
    context_window: null,
    release_date: "2025-06-24",
    architecture: "Diffusion",
    status: "deprecated",
    is_api_available: true,
    modalities: ["text", "image"],
    capabilities: { image_generation: true, image_editing: true },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "imagen-4-ultra": {
    name: "Imagen 4 Ultra",
    description:
      "Highest-fidelity Imagen 4 tier for premium image generation. It is deprecated in favor of Gemini 3.1 Flash Image.",
    category: "image_generation",
    context_window: null,
    release_date: "2025-06-24",
    architecture: "Diffusion",
    status: "deprecated",
    is_api_available: true,
    modalities: ["text", "image"],
    capabilities: { image_generation: true, image_editing: true },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },

  // ---- Video generation ----
  "veo-2": {
    name: "Veo 2",
    description:
      "Historical Google video generation model. Its Gemini API endpoint was shut down on June 30, 2026.",
    category: "video",
    context_window: null,
    release_date: "2025-04-09",
    architecture: "Diffusion (Video)",
    status: "archived",
    is_api_available: false,
    modalities: ["text", "image", "video"],
    capabilities: { video_generation: true },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "veo-3.1-generate-preview": {
    name: "Veo 3.1 Preview",
    description:
      "Google's latest flagship video-generation model with stronger controllability, cinematic output, and native audio generation.",
    category: "video",
    context_window: null,
    release_date: "2025-10-15",
    architecture: "Diffusion (Video)",
    status: "preview",
    is_api_available: true,
    modalities: ["text", "image", "video", "audio"],
    capabilities: { video_generation: true, text_to_speech: true },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "veo-3.1-fast-generate-preview": {
    name: "Veo 3.1 Fast Preview",
    description:
      "Faster Veo 3.1 variant for iterative video ideation and lower-latency creative workflows.",
    category: "video",
    context_window: null,
    release_date: "2025-10-15",
    architecture: "Diffusion (Video)",
    status: "preview",
    is_api_available: true,
    modalities: ["text", "image", "video", "audio"],
    capabilities: { video_generation: true, text_to_speech: true },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "veo-3.1-lite-generate-preview": {
    name: "Veo 3.1 Lite Preview",
    description:
      "Lighter Veo 3.1 variant for faster video ideation and lower-cost video generation workloads.",
    category: "video",
    context_window: null,
    release_date: "2026-03-31",
    architecture: "Diffusion (Video)",
    status: "preview",
    is_api_available: true,
    modalities: ["text", "image", "video", "audio"],
    capabilities: { video_generation: true, text_to_speech: true },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "veo-3": {
    name: "Veo 3",
    description:
      "Historical Veo 3 video-generation family. Its stable Gemini API endpoints were shut down on June 30, 2026.",
    category: "video",
    context_window: null,
    release_date: "2025-09-09",
    architecture: "Diffusion (Video)",
    status: "archived",
    is_api_available: false,
    modalities: ["text", "image", "video", "audio"],
    capabilities: { video_generation: true, text_to_speech: true },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
};

const GOOGLE_KNOWN_MODEL_FAMILY_PREFIXES = [
  "gemma-3n-",
  "gemma-3-",
  "gemma-4-",
] as const;

const GOOGLE_EXACT_MODEL_ALIASES: Record<string, string> = {
  "gemini-flash-latest": "gemini-3.6-flash",
  "gemini-flash-lite-latest": "gemini-3.5-flash-lite",
  "gemini-pro-latest": "gemini-3.1-pro-preview",
  "gemini-3.1-pro": "gemini-3.1-pro-preview",
  "gemini-3.1-flash-live": "gemini-3.1-flash-live-preview",
  "gemini-3.1-flash-tts": "gemini-3.1-flash-tts-preview",
  "lyria-3-pro": "lyria-3-pro-preview",
  "lyria-3-clip": "lyria-3-clip-preview",
  "veo-3.1": "veo-3.1-generate-preview",
  "veo-3.1-fast": "veo-3.1-fast-generate-preview",
  "veo-3.1-lite": "veo-3.1-lite-generate-preview",
  "gemini-2.0-flash-exp-image-generation": "gemini-2.0-flash",
  "gemini-2.5-flash-native-audio-latest": "gemini-2.5-flash-native",
  "imagen-4.0-generate-001": "imagen-4",
  "imagen-4.0-fast-generate-001": "imagen-4-fast",
  "imagen-4.0-ultra-generate-001": "imagen-4-ultra",
  "veo-2.0-generate-001": "veo-2",
  "veo-3.0-generate-001": "veo-3",
  "veo-3.0-fast-generate-001": "veo-3",
};

export function resolveGoogleKnownModelMeta(modelId: string): KnownModelMeta | undefined {
  const exact = GOOGLE_KNOWN_MODELS[modelId];
  if (exact) return exact;

  const alias = GOOGLE_EXACT_MODEL_ALIASES[modelId];
  if (alias) return GOOGLE_KNOWN_MODELS[alias];

  for (const familyPrefix of GOOGLE_KNOWN_MODEL_FAMILY_PREFIXES) {
    if (modelId.startsWith(familyPrefix)) {
      return GOOGLE_KNOWN_MODELS[familyPrefix.slice(0, -1)];
    }
  }

  return undefined;
}
