import type { KnownModelMeta } from "../build-record";

export const META_KNOWN_MODELS: Record<string, KnownModelMeta> = {
  "llama-3-70b-instruct": {
    name: "Llama 3 70B Instruct",
    description:
      "Meta open-weight instruction model in the Llama 3 family for general chat, reasoning, and coding workloads.",
    category: "llm",
    context_window: 8192,
    release_date: "2024-04-18",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Llama 3 Community License",
    hf_model_id: "meta-llama/Meta-Llama-3-70B-Instruct",
    website_url: "https://huggingface.co/meta-llama/Meta-Llama-3-70B-Instruct",
  },
  "llama-3-1-405b-instruct": {
    name: "Llama 3.1 405B Instruct",
    description:
      "Meta's largest Llama 3.1 open-weight instruct model for frontier reasoning, coding, and multilingual long-context workloads.",
    category: "llm",
    context_window: 131072,
    release_date: "2024-07-23",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Llama 3.1 Community License",
    hf_model_id: "meta-llama/Llama-3.1-405B-Instruct",
    website_url: "https://huggingface.co/meta-llama/Llama-3.1-405B-Instruct",
  },
  "llama-3-3-70b-instruct": {
    name: "Llama 3.3 70B Instruct",
    description:
      "Meta's Llama 3.3 open-weight instruct model for current-generation assistant, reasoning, and coding usage.",
    category: "llm",
    context_window: 131072,
    release_date: "2024-12-06",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Llama 3.3 Community License",
    hf_model_id: "meta-llama/Llama-3.3-70B-Instruct",
    website_url: "https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct",
  },
  "llama-2-70b-chat": {
    name: "Llama 2 70B Chat",
    description:
      "Meta's Llama 2 dialogue-tuned open-weight model for chat and assistant-style workloads.",
    category: "llm",
    context_window: 4096,
    release_date: "2023-07-18",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Llama 2 Community License",
    hf_model_id: "meta-llama/Llama-2-70b-chat-hf",
    website_url: "https://huggingface.co/meta-llama/Llama-2-70b-chat-hf",
  },
  "codellama-34b-instruct": {
    name: "Code Llama 34B Instruct",
    description:
      "Meta open-weight code-specialized instruction model for code generation, editing, and development workflows.",
    category: "code",
    context_window: 16384,
    release_date: "2023-08-24",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      coding: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Llama 2 Community License",
    hf_model_id: "meta-llama/CodeLlama-34b-Instruct-hf",
    website_url: "https://about.fb.com/news/2023/08/code-llama-ai-for-coding/",
  },
  musicgen: {
    name: "MusicGen",
    description:
      "Meta text-to-music generation model family for producing high-quality music from text prompts.",
    category: "speech_audio",
    release_date: "2023-08-02",
    architecture: "Transformer (audio generation)",
    status: "active",
    modalities: ["text", "audio"],
    capabilities: {
      audio_generation: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "CC-BY-NC 4.0",
    hf_model_id: "facebook/musicgen-large",
    website_url: "https://about.fb.com/news/2023/08/audiocraft-generative-ai-for-music-and-audio/",
  },
};
