import type { KnownModelMeta } from "../build-record";

export const META_KNOWN_MODELS: Record<string, KnownModelMeta> = {
  "muse-glimmer-30b": {
    name: "Muse Glimmer 30B",
    description:
      "Meta's 30-billion-parameter open-weight multimodal agent model, distilled from Muse Spark for local long-horizon workflows, tool use, coding, visual understanding, and failure recovery on consumer hardware.",
    category: "multimodal",
    context_window: 131072,
    parameter_count: 30000000000,
    release_date: "2026-08-10",
    architecture: "Transformer with dedicated perception encoder",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      vision: true,
      tool_use: true,
      coding: true,
      reasoning: true,
      streaming: true,
      local_inference: true,
    },
    is_api_available: true,
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
    hf_model_id: "meta-models/Muse-Glimmer-30B",
    website_url:
      "https://research.meta.ai/blog/introducing-muse-glimmer-open-agentic-model",
  },
  "muse-spark-1-2": {
    name: "Muse Spark 1.2",
    description:
      "Meta's proprietary coding-focused multimodal reasoning model for long-horizon agents, complex debugging, codebase understanding, tool and computer use, and audio-visual workflows through Meta Model API.",
    category: "multimodal",
    context_window: 1048576,
    release_date: "2026-08-05",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image", "video", "audio", "file"],
    capabilities: {
      vision: true,
      audio: true,
      video: true,
      tool_use: true,
      coding: true,
      reasoning: true,
      computer_use: true,
      streaming: true,
    },
    is_api_available: true,
    is_open_weights: false,
    license: "commercial",
    license_name: null,
    website_url:
      "https://research.meta.ai/blog/introducing-muse-code-and-muse-spark-1-2",
  },
  "muse-image": {
    name: "Muse Image",
    description:
      "Meta's agentic image generation and editing model with search and coding tool use, self-refinement, and multi-reference composition. It is available in Meta products, but Meta has not announced a public model API.",
    category: "image_generation",
    release_date: "2026-07-07",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      image_generation: true,
      image_editing: true,
      tool_use: true,
      coding: true,
      reasoning: true,
    },
    is_api_available: false,
    is_open_weights: false,
    license: "commercial",
    license_name: null,
    website_url:
      "https://ai.meta.com/blog/introducing-muse-image-muse-video-msl/",
  },
  "muse-video": {
    name: "Muse Video",
    description:
      "Meta's preview media generation model for high-fidelity video with native audio. Meta describes it as coming soon to creators and Meta AI, not as a currently available public API or open-weight release.",
    category: "video",
    release_date: "2026-07-07",
    status: "preview",
    modalities: ["text", "video", "audio"],
    capabilities: {
      video_generation: true,
      audio_generation: true,
    },
    is_api_available: false,
    is_open_weights: false,
    license: "commercial",
    license_name: null,
    website_url:
      "https://ai.meta.com/blog/introducing-muse-image-muse-video-msl/",
  },
  "muse-spark-1-1": {
    name: "Muse Spark 1.1",
    description:
      "Previous Meta Muse Spark release retained for compatibility after Muse Spark 1.2. It supports multimodal agentic tasks, coding, tool and computer use, and a 1 million token context window, but is superseded by Muse Spark 1.2 for current development.",
    category: "multimodal",
    context_window: 1048576,
    release_date: "2026-07-09",
    status: "active",
    modalities: ["text", "image", "video", "audio", "file"],
    capabilities: {
      vision: true,
      audio: true,
      video: true,
      tool_use: true,
      coding: true,
      reasoning: true,
      computer_use: true,
      streaming: true,
    },
    is_api_available: true,
    is_open_weights: false,
    license: "commercial",
    license_name: null,
    website_url:
      "https://ai.meta.com/blog/introducing-muse-spark-meta-model-api/",
  },
  "llama-3-8b-instruct": {
    name: "Meta-Llama-3-8B-Instruct",
    description:
      "Meta open-weight instruction model in the Llama 3 family for general chat, reasoning, and coding workloads.",
    category: "llm",
    context_window: 8192,
    release_date: "2024-04-18",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Llama 3 Community License",
    hf_model_id: "meta-llama/Meta-Llama-3-8B-Instruct",
    website_url: "https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct",
  },
  "llama-3-70b-instruct": {
    name: "Llama 3 70B Instruct",
    description:
      "Meta open-weight instruction model in the Llama 3 family for general chat, reasoning, and coding workloads.",
    category: "llm",
    context_window: 8192,
    release_date: "2024-04-18",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Llama 3 Community License",
    hf_model_id: "meta-llama/Meta-Llama-3-70B-Instruct",
    website_url: "https://huggingface.co/meta-llama/Meta-Llama-3-70B-Instruct",
  },
  "llama-3-1-405b-instruct": {
    name: "Llama 3.1 405B Instruct",
    description:
      "Meta's largest Llama 3.1 open-weight instruct model for frontier reasoning, coding, and multilingual long-context workloads.",
    category: "llm",
    context_window: 131072,
    release_date: "2024-07-23",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Llama 3.1 Community License",
    hf_model_id: "meta-llama/Llama-3.1-405B-Instruct",
    website_url: "https://huggingface.co/meta-llama/Llama-3.1-405B-Instruct",
  },
  "llama-3-3-70b-instruct": {
    name: "Llama 3.3 70B Instruct",
    description:
      "Meta's Llama 3.3 open-weight instruct model for current-generation assistant, reasoning, and coding usage.",
    category: "llm",
    context_window: 131072,
    release_date: "2024-12-06",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Llama 3.3 Community License",
    hf_model_id: "meta-llama/Llama-3.3-70B-Instruct",
    website_url: "https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct",
  },
  "llama-2-70b-chat": {
    name: "Llama 2 70B Chat",
    description:
      "Meta's Llama 2 dialogue-tuned open-weight model for chat and assistant-style workloads.",
    category: "llm",
    context_window: 4096,
    release_date: "2023-07-18",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Llama 2 Community License",
    hf_model_id: "meta-llama/Llama-2-70b-chat-hf",
    website_url: "https://huggingface.co/meta-llama/Llama-2-70b-chat-hf",
  },
  "codellama-34b-instruct": {
    name: "Code Llama 34B Instruct",
    description:
      "Meta open-weight code-specialized instruction model for code generation, editing, and development workflows.",
    category: "code",
    context_window: 16384,
    release_date: "2023-08-24",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      coding: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Llama 2 Community License",
    hf_model_id: "meta-llama/CodeLlama-34b-Instruct-hf",
    website_url: "https://about.fb.com/news/2023/08/code-llama-ai-for-coding/",
  },
  musicgen: {
    name: "MusicGen",
    description:
      "Meta text-to-music generation model family for producing high-quality music from text prompts.",
    category: "speech_audio",
    release_date: "2023-08-02",
    architecture: "Transformer (audio generation)",
    status: "active",
    modalities: ["text", "audio"],
    capabilities: {
      audio_generation: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "CC-BY-NC 4.0",
    hf_model_id: "facebook/musicgen-large",
    website_url: "https://about.fb.com/news/2023/08/audiocraft-generative-ai-for-music-and-audio/",
  },
};
