import type { KnownModelMeta } from "../build-record";

export const MISTRAL_KNOWN_MODELS: Record<string, KnownModelMeta> = {
  "robostral-navigate": {
    name: "Robostral Navigate",
    description:
      "Mistral AI's 8B specialized vision-language model for autonomous robot navigation from a single RGB camera and natural-language instructions. Access is currently offered through direct engagement rather than a public model API.",
    category: "specialized",
    parameter_count: 8_000_000_000,
    release_date: "2026-07-08",
    architecture: "Vision-language navigation model",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      vision: true,
      reasoning: true,
      robotics: true,
    },
    is_api_available: false,
    is_open_weights: false,
    license: "commercial",
    license_name: null,
    website_url: "https://mistral.ai/news/robostral-navigate/",
  },
  "mistral-ocr-4-0": {
    name: "Mistral OCR 4",
    description:
      "Mistral AI's current Document AI OCR service with paragraph-level bounding boxes, structural block labels, and document understanding through the OCR API.",
    category: "specialized",
    release_date: "2026-06-23",
    status: "active",
    modalities: ["text", "image", "file"],
    capabilities: {
      vision: true,
      ocr: true,
      document_understanding: true,
    },
    is_api_available: true,
    is_open_weights: false,
    license: "commercial",
    license_name: "Premier",
    website_url: "https://docs.mistral.ai/models/model-cards/ocr-4-0",
  },
  "labs-leanstral-1-5": {
    name: "Leanstral 1.5",
    description:
      "Mistral AI's open-weight Lean 4 code agent for automated theorem proving, formal proof engineering, and autoformalization.",
    category: "code",
    context_window: 262144,
    parameter_count: 119_000_000_000,
    release_date: "2026-06-30",
    architecture: "Sparse mixture-of-experts transformer",
    status: "preview",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      tool_use: true,
      streaming: true,
    },
    is_api_available: true,
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
    website_url:
      "https://docs.mistral.ai/models/model-cards/leanstral-1-5",
  },
  "mistral-medium-3-5": {
    name: "Mistral Medium 3.5",
    description:
      "Mistral AI's frontier-class open-weight multimodal model optimized for agentic and coding use cases, with a 256K context window.",
    category: "multimodal",
    context_window: 262144,
    parameter_count: 128_000_000_000,
    release_date: "2026-04-28",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image", "file"],
    capabilities: {
      vision: true,
      reasoning: true,
      coding: true,
      tool_use: true,
      streaming: true,
    },
    is_api_available: true,
    is_open_weights: true,
    license: "open_source",
    license_name: "Modified MIT",
    website_url:
      "https://docs.mistral.ai/models/model-cards/mistral-medium-3-5-26-04",
  },
  "voxtral-mini-tts-2603": {
    name: "Voxtral TTS",
    description:
      "Mistral AI's open-weight text-to-speech model with zero-shot voice cloning, multilingual speech generation, and streaming output.",
    category: "speech_audio",
    release_date: "2026-03-23",
    status: "active",
    modalities: ["text", "audio"],
    capabilities: {
      audio_generation: true,
      voice_cloning: true,
      streaming: true,
    },
    is_api_available: true,
    is_open_weights: true,
    license: "research_only",
    license_name: "CC-BY-NC 4.0",
    website_url:
      "https://docs.mistral.ai/models/model-cards/voxtral-tts-26-03",
  },
  "mistral-small-2603": {
    name: "Mistral Small 4",
    description:
      "Mistral AI's open-weight hybrid multimodal model combining instruct, reasoning, coding, and agentic capabilities with 119B total and 6.5B active parameters.",
    category: "multimodal",
    context_window: 262144,
    parameter_count: 119_000_000_000,
    release_date: "2026-03-16",
    architecture: "Sparse mixture-of-experts transformer",
    status: "active",
    modalities: ["text", "image", "file"],
    capabilities: {
      vision: true,
      reasoning: true,
      coding: true,
      tool_use: true,
      streaming: true,
    },
    is_api_available: true,
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
    website_url:
      "https://docs.mistral.ai/models/model-cards/mistral-small-4-0-26-03",
  },
  "mistral-moderation-2603": {
    name: "Mistral Moderation 2",
    description:
      "Mistral AI's current multilingual moderation model with jailbreak detection and a 128K context window.",
    category: "specialized",
    context_window: 131072,
    release_date: "2026-03-01",
    status: "active",
    modalities: ["text"],
    capabilities: {
      moderation: true,
      streaming: true,
    },
    is_api_available: true,
    is_open_weights: false,
    license: "commercial",
    license_name: "Premier",
    website_url:
      "https://docs.mistral.ai/models/model-cards/mistral-moderation-26-03",
  },
  "voxtral-mini-2602": {
    name: "Voxtral Mini Transcribe 2",
    description:
      "Mistral AI's current hosted transcription model for multilingual speech recognition, diarization, context biasing, and word-level timestamps.",
    category: "speech_audio",
    release_date: "2026-02-04",
    status: "active",
    modalities: ["audio", "text"],
    capabilities: {
      transcription: true,
      diarization: true,
      streaming: false,
    },
    is_api_available: true,
    is_open_weights: false,
    license: "commercial",
    license_name: "Premier",
    website_url:
      "https://docs.mistral.ai/models/model-cards/voxtral-mini-transcribe-26-02",
  },
  "voxtral-mini-transcribe-realtime-2602": {
    name: "Voxtral Mini Transcribe Realtime",
    description:
      "Mistral AI's open-weight 4B realtime transcription model for low-latency multilingual speech recognition and edge deployment.",
    category: "speech_audio",
    parameter_count: 4_000_000_000,
    release_date: "2026-02-04",
    status: "active",
    modalities: ["audio", "text"],
    capabilities: {
      transcription: true,
      streaming: true,
    },
    is_api_available: true,
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
    website_url:
      "https://docs.mistral.ai/models/model-cards/voxtral-mini-transcribe-realtime-26-02",
  },
  "mistral-large-2512": {
    name: "Mistral Large 3",
    description:
      "Mistral AI's open-weight general-purpose multimodal mixture-of-experts model with 675B total and 41B active parameters.",
    category: "multimodal",
    context_window: 262144,
    parameter_count: 675_000_000_000,
    release_date: "2025-12-02",
    architecture: "Sparse mixture-of-experts transformer",
    status: "active",
    modalities: ["text", "image", "file"],
    capabilities: {
      vision: true,
      reasoning: true,
      coding: true,
      tool_use: true,
      streaming: true,
    },
    is_api_available: true,
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
    website_url:
      "https://docs.mistral.ai/models/model-cards/mistral-large-3-25-12",
  },
  "mixtral-8x7b-instruct-v0-1": {
    name: "Mixtral 8x7B Instruct v0.1",
    description:
      "Mistral AI open-weight mixture-of-experts instruct model for broad general-purpose reasoning and coding workloads.",
    category: "llm",
    context_window: 32768,
    release_date: "2023-12-11",
    architecture: "Sparse mixture-of-experts transformer",
    status: "archived",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      streaming: true,
    },
    is_api_available: false,
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
    hf_model_id: "mistralai/Mixtral-8x7B-Instruct-v0.1",
    website_url: "https://mistral.ai/news/mixtral-of-experts",
  },
  "mistral-7b-instruct-v0-2": {
    name: "Mistral 7B Instruct v0.2",
    description:
      "Mistral AI open-weight instruct model with upgraded context and strong efficiency for production chat and coding use.",
    category: "llm",
    context_window: 32768,
    release_date: "2023-12-11",
    architecture: "Transformer",
    status: "archived",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      streaming: true,
    },
    is_api_available: false,
    is_open_weights: true,
    license: "open_source",
    license_name: "Apache 2.0",
    hf_model_id: "mistralai/Mistral-7B-Instruct-v0.2",
    website_url: "https://docs.mistral.ai/models/mistral-7b-0-2",
  },
};
