import type { KnownModelMeta } from "../build-record";

export const MOONSHOT_KNOWN_MODELS: Record<string, KnownModelMeta> = {
  "kimi-k2.6": {
    name: "Kimi K2.6",
    description:
      "Moonshot AI's latest multimodal model with stronger long-horizon coding, agent execution, and vision performance, released as an open-source flagship.",
    category: "multimodal",
    context_window: 256000,
    release_date: "2026-04-20",
    architecture: "Transformer (MoE)",
    status: "active",
    modalities: ["text", "image", "video"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Open weights",
    website_url: "https://www.kimi.com/blog/kimi-k2-6",
  },
  "kimi-k2.5": {
    name: "Kimi K2.5",
    description:
      "Kimi's most intelligent model, supporting visual and text input, dialogue, and agent-style task execution for complex workflows.",
    category: "multimodal",
    context_window: 256000,
    release_date: "2026-01-27",
    architecture: "Transformer (MoE)",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "kimi-k2": {
    name: "Kimi K2",
    description:
      "Moonshot's K2 base model with exceptional coding and agent capabilities, built on a MoE architecture with strong instruction following.",
    category: "llm",
    context_window: 256000,
    release_date: "2025-09-05",
    architecture: "Transformer (MoE)",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "kimi-k2-thinking": {
    name: "Kimi K2 Thinking",
    description:
      "Dedicated Kimi thinking model with strong deep-reasoning and multi-step tool-use performance for agentic tasks.",
    category: "llm",
    context_window: 256000,
    release_date: "2025-11-06",
    architecture: "Transformer (MoE reasoning)",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      function_calling: true,
      extended_thinking: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "kimi-k2-thinking-turbo": {
    name: "Kimi K2 Thinking Turbo",
    description:
      "Lower-latency Kimi K2 thinking variant for multi-step reasoning, tool calling, and agent-style orchestration.",
    category: "llm",
    context_window: 256000,
    release_date: "2025-11-06",
    architecture: "Transformer (MoE reasoning)",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      function_calling: true,
      extended_thinking: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "kimi-k2-0905-preview": {
    name: "Kimi K2 0905 Preview",
    description:
      "Preview release of Kimi K2 with a 256K context window and stronger code-generation capabilities.",
    category: "llm",
    context_window: 256000,
    release_date: "2025-09-05",
    architecture: "Transformer (MoE)",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "kimi-k2-turbo-preview": {
    name: "Kimi K2 Turbo Preview",
    description:
      "Fast preview variant of Kimi K2 that tracks the latest K2 capabilities while increasing output speed for production interactions.",
    category: "llm",
    context_window: 256000,
    release_date: "2025-09-05",
    architecture: "Transformer (MoE)",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
};

export function resolveMoonshotKnownModelMeta(modelId: string): KnownModelMeta | undefined {
  return MOONSHOT_KNOWN_MODELS[modelId] ?? MOONSHOT_KNOWN_MODELS[modelId.toLowerCase()];
}
