import type { KnownModelMeta } from "../build-record";

export const XAI_KNOWN_MODELS: Record<string, KnownModelMeta> = {
  "grok-4.1": {
    name: "Grok 4.1",
    description:
      "xAI's latest flagship Grok model for advanced reasoning, coding, and long-horizon agent workflows.",
    category: "llm",
    context_window: 256000,
    release_date: "2025-11-17",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "grok-4-fast": {
    name: "Grok 4 Fast",
    description:
      "Lower-latency Grok 4 variant that preserves strong reasoning and coding performance at lower cost and faster response times.",
    category: "llm",
    context_window: 256000,
    release_date: "2025-09-19",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "grok-4": {
    name: "Grok 4",
    description:
      "Frontier Grok model built for demanding enterprise reasoning, coding, and agentic task execution.",
    category: "llm",
    context_window: 256000,
    release_date: "2025-08-20",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "grok-code-fast-1": {
    name: "Grok Code Fast 1",
    description:
      "Fast and efficient xAI reasoning model designed specifically for coding applications and autonomous software workflows.",
    category: "code",
    context_window: 256000,
    release_date: "2025-08-26",
    architecture: "Transformer (code)",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "grok-3": {
    name: "Grok 3",
    description:
      "General-purpose Grok frontier model for reasoning, coding, and multimodal assistant workflows.",
    category: "llm",
    context_window: 131072,
    release_date: "2025-02-17",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "grok-3-mini": {
    name: "Grok 3 Mini",
    description:
      "Smaller Grok 3 variant optimized for lower latency and lower-cost reasoning and coding tasks.",
    category: "llm",
    context_window: 131072,
    release_date: "2025-02-17",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
};
