import type { KnownModelMeta } from "../build-record";

export const XAI_KNOWN_MODELS: Record<string, KnownModelMeta> = {
  "grok-4.1": {
    name: "Grok 4.1",
    description:
      "xAI's latest flagship Grok model for advanced reasoning, coding, and long-horizon agent workflows.",
    category: "llm",
    context_window: 256000,
    release_date: "2025-11-17",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
    website_url: "https://docs.x.ai/docs/models/grok-4.1",
  },
  "grok-4-fast": {
    name: "Grok 4 Fast",
    description:
      "Lower-latency Grok 4 variant that preserves strong reasoning and coding performance at lower cost and faster response times.",
    category: "llm",
    context_window: 256000,
    release_date: "2025-09-19",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
    website_url: "https://data.x.ai/2025-09-19-grok-4-fast-model-card.pdf",
  },
  "grok-4": {
    name: "Grok 4",
    description:
      "Frontier Grok model built for demanding enterprise reasoning, coding, and agentic task execution.",
    category: "llm",
    context_window: 256000,
    release_date: "2025-08-20",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
    website_url: "https://data.x.ai/2025-08-20-grok-4-model-card.pdf",
  },
  "grok-4-20": {
    name: "Grok 4.20",
    description:
      "Updated Grok 4 family release for multimodal assistant, reasoning, and coding workflows.",
    category: "multimodal",
    context_window: 256000,
    release_date: "2026-03-31",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
    website_url: "https://docs.x.ai/docs/models",
  },
  "grok-4-20-multi-agent": {
    name: "Grok 4.20 Multi-Agent",
    description:
      "Grok 4.20 workflow variant designed for coordinated multi-agent orchestration and complex tool use.",
    category: "multimodal",
    context_window: 256000,
    release_date: "2026-03-31",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
      agentic_workflows: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
    website_url: "https://docs.x.ai/docs/models",
  },
  "grok-code-fast-1": {
    name: "Grok Code Fast 1",
    description:
      "Fast and efficient xAI reasoning model designed specifically for coding applications and autonomous software workflows.",
    category: "code",
    context_window: 256000,
    release_date: "2025-08-26",
    architecture: "Transformer (code)",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "grok-3": {
    name: "Grok 3",
    description:
      "General-purpose Grok frontier model for reasoning, coding, and multimodal assistant workflows.",
    category: "llm",
    context_window: 131072,
    release_date: "2025-02-17",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "grok-3-mini": {
    name: "Grok 3 Mini",
    description:
      "Smaller Grok 3 variant optimized for lower latency and lower-cost reasoning and coding tasks.",
    category: "llm",
    context_window: 131072,
    release_date: "2025-02-17",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "grok-imagine-image": {
    name: "Grok Imagine Image",
    description:
      "xAI's native image generation model for creating and editing images from text prompts inside the Grok Imagine family.",
    category: "image_generation",
    architecture: "Diffusion / multimodal generation",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      image_generation: true,
      image_editing: true,
      vision: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "grok-imagine-video": {
    name: "Grok Imagine Video",
    description:
      "xAI's native video generation model for producing audiovisual clips from text prompts in the Grok Imagine family.",
    category: "video",
    architecture: "Multimodal video generation",
    status: "active",
    modalities: ["text", "image", "video", "audio"],
    capabilities: {
      video_generation: true,
      vision: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "grok-imagine-r2v": {
    name: "Grok Imagine Reference to Video",
    description:
      "xAI's Grok Imagine video model for generating new audiovisual clips guided by a reference image and text prompt.",
    category: "video",
    architecture: "Multimodal video generation",
    status: "active",
    modalities: ["text", "image", "video", "audio"],
    capabilities: {
      video_generation: true,
      vision: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "grok-imagine-video-extension": {
    name: "Grok Imagine Video Extension",
    description:
      "xAI's Grok Imagine video model for extending an existing video clip with a guided next-scene continuation.",
    category: "video",
    architecture: "Multimodal video generation",
    status: "active",
    modalities: ["text", "video", "audio"],
    capabilities: {
      video_generation: true,
      video_editing: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
};
