import type { KnownModelMeta } from "../build-record";

export const ZAI_KNOWN_MODELS: Record<string, KnownModelMeta> = {
  "glm-5": {
    name: "GLM-5",
    description:
      "Z.ai's flagship reasoning and coding model family for long-horizon agentic workflows.",
    category: "llm",
    context_window: 128000,
    release_date: "2026-02-12",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "glm-5-turbo": {
    name: "GLM-5 Turbo",
    description:
      "Lower-latency GLM-5 variant focused on efficient coding and long-context agent runs.",
    category: "llm",
    context_window: 128000,
    release_date: "2026-03-15",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "glm-4.7": {
    name: "GLM-4.7",
    description: "Z.ai general-purpose GLM series model for production text workloads.",
    category: "llm",
    context_window: 128000,
    release_date: "2026-01-01",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "glm-4.6": {
    name: "GLM-4.6",
    description: "Z.ai GLM series model for general text generation and reasoning tasks.",
    category: "llm",
    context_window: 128000,
    release_date: "2025-12-01",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "glm-4.5": {
    name: "GLM-4.5",
    description: "Earlier GLM reasoning model still served through the Z.ai API platform.",
    category: "llm",
    context_window: 128000,
    release_date: "2025-10-01",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "glm-4-32b-0414-128k": {
    name: "GLM-4 32B 0414 128K",
    description: "Long-context GLM 4 model with a 128K context window.",
    category: "llm",
    context_window: 128000,
    release_date: "2025-04-14",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "glm-4.6v": {
    name: "GLM-4.6V",
    description: "Multimodal GLM variant for image and document understanding.",
    category: "multimodal",
    context_window: 128000,
    release_date: "2025-12-01",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      vision: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "glm-4.5v": {
    name: "GLM-4.5V",
    description: "Earlier GLM multimodal model for visual reasoning and OCR-adjacent tasks.",
    category: "multimodal",
    context_window: 128000,
    release_date: "2025-10-01",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      vision: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "glm-ocr": {
    name: "GLM OCR",
    description: "Document and OCR-focused GLM visual model served through Z.ai docs.",
    category: "multimodal",
    context_window: 64000,
    release_date: "2025-12-01",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      vision: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "glm-image": {
    name: "GLM Image",
    description: "Z.ai image generation model surfaced in the official docs catalog.",
    category: "image_generation",
    release_date: "2025-12-01",
    architecture: "Diffusion Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      image_generation: true,
      streaming: false,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "glm-asr-2512": {
    name: "GLM ASR 2512",
    description: "Audio transcription model listed in the official Z.ai docs sitemap.",
    category: "audio",
    release_date: "2025-12-01",
    architecture: "Transformer",
    status: "active",
    modalities: ["audio", "text"],
    capabilities: {
      speech_to_text: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
};
