import type { KnownModelMeta } from "../build-record";

export const ZAI_KNOWN_MODELS: Record<string, KnownModelMeta> = {
  "glm-5": {
    name: "GLM-5",
    description:
      "Z.ai's flagship reasoning and coding model family for long-horizon agentic workflows.",
    category: "llm",
    context_window: 128000,
    release_date: "2026-02-12",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
    website_url: "https://docs.z.ai/guides/llm/glm-5",
  },
  "glm-5.1": {
    name: "GLM-5.1",
    description:
      "Z.ai's updated flagship reasoning and coding model family with stronger agentic performance and longer-context production workflows.",
    category: "llm",
    context_window: 202752,
    release_date: "2026-04-03",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
    website_url: "https://docs.z.ai/devpack/using5.1",
  },
  "glm-5-turbo": {
    name: "GLM-5 Turbo",
    description:
      "Lower-latency GLM-5 variant focused on efficient coding and long-context agent runs.",
    category: "llm",
    context_window: 128000,
    release_date: "2026-03-15",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "glm-4.7": {
    name: "GLM-4.7",
    description: "Z.ai general-purpose GLM series model for production text workloads.",
    category: "llm",
    context_window: 128000,
    release_date: "2026-01-01",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "glm-4.6": {
    name: "GLM-4.6",
    description: "Z.ai GLM series model for general text generation and reasoning tasks.",
    category: "llm",
    context_window: 128000,
    release_date: "2025-12-01",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "glm-4.5": {
    name: "GLM-4.5",
    description: "Earlier GLM reasoning model still served through the Z.ai API platform.",
    category: "llm",
    context_window: 128000,
    release_date: "2025-10-01",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "glm-4-32b-0414-128k": {
    name: "GLM-4 32B 0414 128K",
    description: "Long-context GLM 4 model with a 128K context window.",
    category: "llm",
    context_window: 128000,
    release_date: "2025-04-14",
    architecture: "Transformer",
    status: "active",
    modalities: ["text"],
    capabilities: {
      reasoning: true,
      coding: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "glm-4.6v": {
    name: "GLM-4.6V",
    description: "Multimodal GLM variant for image and document understanding.",
    category: "multimodal",
    context_window: 128000,
    release_date: "2025-12-01",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      vision: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "glm-4.5v": {
    name: "GLM-4.5V",
    description: "Earlier GLM multimodal model for visual reasoning and OCR-adjacent tasks.",
    category: "multimodal",
    context_window: 128000,
    release_date: "2025-10-01",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      vision: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
  },
  "glm-ocr": {
    name: "GLM OCR",
    description: "Document and OCR-focused GLM visual model served through Z.ai docs.",
    category: "multimodal",
    context_window: 64000,
    release_date: "2025-12-01",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      vision: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
    website_url: "https://docs.z.ai/guides/vlm/glm-ocr",
  },
  "glm-5v-turbo": {
    name: "GLM-5V-Turbo",
    description:
      "Z.ai's native multimodal coding and agent model for visual programming, image and video understanding, and long-context multimodal workflows.",
    category: "multimodal",
    context_window: 202752,
    release_date: "2026-04-02",
    architecture: "Transformer",
    status: "active",
    modalities: ["text", "image", "video"],
    capabilities: {
      reasoning: true,
      coding: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
    website_url: "https://docs.z.ai/guides/vlm/glm-5v-turbo",
  },
  "glm-image": {
    name: "GLM Image",
    description: "Z.ai image generation model surfaced in the official docs catalog.",
    category: "image_generation",
    release_date: "2025-12-01",
    architecture: "Diffusion Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      image_generation: true,
      streaming: false,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
    website_url: "https://docs.z.ai/guides/image/glm-image",
  },
  "glm-asr-2512": {
    name: "GLM ASR 2512",
    description: "Audio transcription model listed in the official Z.ai docs sitemap.",
    category: "speech_audio",
    release_date: "2025-12-01",
    architecture: "Transformer",
    status: "active",
    modalities: ["audio", "text"],
    capabilities: {
      speech_to_text: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
    website_url: "https://docs.z.ai/guides/audio/glm-asr-2512",
  },
  "autoglm-phone-multilingual": {
    name: "AutoGLM Phone Multilingual",
    description:
      "Z.ai's multimodal mobile automation framework for understanding phone screens and executing real actions across Android apps.",
    category: "agentic_browser",
    release_date: "2025-12-11",
    architecture: "Multimodal agent framework",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      reasoning: true,
      vision: true,
      function_calling: true,
      streaming: true,
    },
    is_open_weights: false,
    license: "commercial",
    license_name: null,
    website_url: "https://docs.z.ai/guides/vlm/autoglm-phone-multilingual",
  },
  "cogview-4": {
    name: "CogView-4",
    description:
      "Z.ai's open-source text-to-image model for bilingual prompt following, high-resolution generation, and creative image workflows.",
    category: "image_generation",
    release_date: "2025-03-04",
    architecture: "Diffusion Transformer",
    status: "active",
    modalities: ["text", "image"],
    capabilities: {
      image_generation: true,
    },
    is_open_weights: true,
    license: "open_source",
    license_name: "Open weights",
    website_url: "https://docs.z.ai/guides/image/cogview-4",
  },
};

const ZAI_EXACT_MODEL_ALIASES: Record<string, string> = {
  "zai-org-glm-5": "glm-5",
  "zai-org-glm-5-1": "glm-5.1",
};

export function resolveZAIKnownModelMeta(modelId: string): KnownModelMeta | undefined {
  const exact = ZAI_KNOWN_MODELS[modelId];
  if (exact) return exact;

  const alias = ZAI_EXACT_MODEL_ALIASES[modelId];
  if (alias) return ZAI_KNOWN_MODELS[alias];

  return undefined;
}
